# Global settings for Aniela's Portfolio website

# Site settings
title: Aniela Nowak -- Artistic Portfolio Website
email: anielka.nowak77@gmail.com
description: 'A portfolio website for Aniela Nowak'
url: "http://anielanowak.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
footer_text: 'This text is footer text. Footer text goes here.'

# Build settings
markdown: kramdown


